### PR TITLE
[CHG] added ShowPropertyPage method to DirectShowDevice class

### PR DESCRIPTION
**Pull request by kekyo**
Moved from #110.

### CODE REVIEW

**Comment by kekyo** [comment]
@flat-eric147 I created a branch with your commit and some code changed:

* Changed WPF UI implementation with MVVM (Uses Epoxy).
  * Since Avalonia's implementation was more advanced, we have ported it to WPF and implemented your process based on it.
  * It should now be almost identical to the Avalonia implementation.
* Bit changed signature: `device.ShowPropertyChangedAsync(IntPtr handle, CancellationToken ct)`
   (But the CancellationToken is not handled. It is contains technical difficulty, so ignored now.)

Would you be willing to give it a try?

**Comment by flat-eric147** [comment]
Just tested and works very well. Only thing I would change is to start with the first capture source you find, just as it was before. It gives you a better user experience, especially if you run the sample the first time, it's not immediately clear that you have to select a source from the drop down.

**Comment by kekyo** [comment]
Improved it! If there are no problems, will be merged.

**Comment by flat-eric147** [comment]
Tested, I approve it :-D Thank you!

**Pull request merged**
